# Generated by Django 5.0.7 on 2024-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='montag',
            name='nshr',
            field=models.BooleanField(null=True),
        ),
    ]
