# Generated by Django 5.0.7 on 2024-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_employee_mony_employee_to_get'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee_mony',
            new_name='employeeMony',
        ),
        migrations.RenameField(
            model_name='employeemony',
            old_name='employee_name',
            new_name='employeeName',
        ),
        migrations.RenameField(
            model_name='employeemony',
            old_name='mony_to_get',
            new_name='monyToGet',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mony',
        ),
        migrations.AddField(
            model_name='employee',
            name='mony',
            field=models.ManyToManyField(blank=True, null=True, to='main.employee_mony'),
        ),
    ]
