# Generated by Django 5.0.7 on 2024-07-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_employeename_mony_name_alter_employee_mony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificate',
            name='who',
        ),
        migrations.AddField(
            model_name='ips',
            name='red_card',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='montagOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s3r', models.CharField(max_length=255)),
                ('kmwahed_number', models.CharField(max_length=255)),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ips')),
                ('place_to_get', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
            ],
        ),
    ]
