# Generated by Django 5.0.7 on 2024-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_place_employee_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_mony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mony_to_get', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_to_get', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
