# Generated by Django 5.0.7 on 2024-07-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_mony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_mony',
            name='employee_to_get',
        ),
    ]
