# Generated by Django 5.0.7 on 2024-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_employeemony_mony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mony',
            old_name='employeeName',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='mony',
            field=models.ManyToManyField(blank=True, null=True, to='main.mony'),
        ),
    ]
